version: '3.8'

services:
  postgres_test:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=class_booking
      - POSTGRES_USER=class_booking
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - members_test
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
networks:
  members_test:
    driver: bridge
