version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=class_booking
      - POSTGRES_USER=class_booking
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    networks:
      - class_booking
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: psql -h localhost -U class_booking -c '\q' || exit 1
      interval: 1s
      retries: 5
      start_period: 1s
      timeout: 10s
networks:
  class_booking:
    driver: bridge
